# Search related
search:
  fit_by_residual: false
  device: 'cpu'  # cuda
  batch_size: 'auto'
  sketch_dir: 'sketches/'
  iterations: 10

# Data related
data:
  directory_path: 'data/country/seller'
  buyer_csv: 'data/country/buyer/buyer_gini.csv'
  join_keys: 
    - ['country']
  target_feature: 'value'
  one_target_feature: false
  need_to_clean_data: true
  entity_linking_percentage: [2,5,10]

# Experiment related
experiment:
  plot_results: true
  save_results: true
  results_dir: 'results/'

# logging
logging:
  level: 'ERROR'
  file: 'logs/experiment.log'